import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

class SupabaseManager:
    def __init__(self):
        url = os.environ.get("SUPABASE_URL")
        key = os.environ.get("SUPABASE_KEY")
        if not url or not key:
            raise ValueError("Supabase credentials not found in environment variables.")
        self.client: Client = create_client(url, key)

    def insert_article(self, article_data):
        """Inserts a new article draft."""
        return self.client.table("articles").insert(article_data).execute()

    def get_sources(self):
        """Retrieves active sources."""
        return self.client.table("sources").select("*").eq("is_active", True).execute()
    
    def get_categories(self):
        """Retrieves categories."""
        return self.client.table("categories").select("id, name, slug").execute()

    def fetch_articles_by_status(self, status='draft'):
        """Fetches articles by status."""
        return self.client.table("articles").select("*").eq("status", status).execute()

    def update_article_status(self, article_id, status):
        """Updates article status."""
        return self.client.table("articles").update({"status": status}).eq("id", article_id).execute()

    def get_or_create_category(self, name):
        """Retrieves a category by name, or creates it if it doesn't exist."""
        # Simple slug generation (not perfect but functional for auto-gen)
        # In a real app, use a proper slugify library
        slug = name.lower().replace(" ", "-").replace("/", "-")
        
        # 1. Try to find existing
        res = self.client.table("categories").select("id").eq("name", name).execute()
        if res.data:
            return res.data[0]['id']
            
        # 1b. Try by slug just in case
        res = self.client.table("categories").select("id").eq("slug", slug).execute()
        if res.data:
            return res.data[0]['id']

        # 2. Create new
        try:
            new_cat = {"name": name, "slug": slug, "description": "Auto-generated by AI"}
            res = self.client.table("categories").insert(new_cat).execute()
            if res.data:
                return res.data[0]['id']
        except Exception as e:
            print(f"Error creating category {name}: {e}")
            # Fallback: maybe try again with a random suffix for slug if unique constraint failed
            import uuid
            slug = f"{slug}-{str(uuid.uuid4())[:8]}"
            new_cat = {"name": name, "slug": slug, "description": "Auto-generated by AI (Retry)"}
            res = self.client.table("categories").insert(new_cat).execute()
            if res.data:
                return res.data[0]['id']
        
        return None

if __name__ == "__main__":
    # Test connection
    try:
        db = SupabaseManager()
        print("Supabase connection successful.")
    except Exception as e:
        print(f"Supabase connection failed: {e}")
